### PR TITLE
Launcher and chk script

### LINKED ISSUE #117: Add script to stop mount after Kstars crash
if kstars crashes, the mount remains in traking without any control,  ending up slamming.  Need an external script that verifies the presence of a connection to INDI and if it does not find the script sends everything to the park

see[ INDI SCRIPT ](https://indilib.org/develop/developer-manual/104-scripting.html)

### LINKED ISSUE #135: add chk free disk space in lxpanel

### PR DESCRIPTION
**Pull request by Andre87osx**

### CODE REVIEW

File: Script/AstroPi.sh [hunk 1]
```diff
@@ -213,8 +213,16 @@ sources=/etc/apt/sources.list.d/astroberry.list
 		echo "$password" | sudo -S cp "$GitDir"/Script/.Update.sh /usr/bin/.Update.sh
 		(($? != 0)) && zenity --error --width=$W --text="Something went wrong in <b>Updating .Update.sh</b>\nContact support at <b>https://github.com/Andre87osx/AstroPi-system/issues</b>" --title="AstroPi System $AstroPi_v" && exit 1
 		echo "$password" | sudo -S chmod +x /usr/bin/.Update.sh
+		# Copy kstars.sh and make executable
+		echo "$password" | sudo -S cp "$GitDir"/Script/kstars.sh /usr/bin/.Update.sh
```
Comment (Andre87osx) [inline Script/AstroPi.sh:217]: bug copy in bin not change name file
